FROM node:21.1 as build
WORKDIR /client

COPY ./package.json .
COPY ./package-lock.json .
COPY ./pnpm-lock.yaml .
RUN npm i -g npm
RUN npm i

COPY . .

RUN npm run build

FROM nginx

COPY --from=build ./client/dist /usr/share/nginx/html