version: "3.8"
services:
  client:
    image: "snipshare-client-prod"
    container_name: "snipshare-client-prod"
    build:
      dockerfile: dockerfile.prod
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules
    ports:
      - "3000:80"

  server:
    image: "snipshare-server-prod"
    container_name: "snipshare-server-prod"
    build:
      dockerfile: dockerfile.prod
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/server
      - node_modules:/server/node_modules
    ports:
      - "2000:2000"

volumes:
  node_modules:
