version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: "snipshare-db"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=snipshare
      - MYSQL_PASSWORD=snipshare
      - MYSQL_DATABASE=snipshare
      # - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
      # - "33060:33060"
    networks:
      - snipshare-network

  server:
    depends_on:
      - db
    image: "snipshare-server-prod"
    container_name: "snipshare-server-prod"
    build:
      context: ./server
      dockerfile: dockerfile.prod
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/server
      - node_modules:/server/node_modules
    ports:
      - "2000:2000"
    networks:
      - snipshare-network

  client:
    depends_on:
      - server
    image: "snipshare-client-prod"
    container_name: "snipshare-client-prod"
    build:
      context: ./client
      dockerfile: dockerfile.prod
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules
    ports:
      - "3000:80"
    networks:
      - snipshare-network

networks:
  snipshare-network:

volumes:
  node_modules:
