#!/bin/sh

## UNIT TESTING
pnpm testOnce || exit 1;

## FORMATTING ONLY STAGED FILES (make sure this is the last one)
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
if [ ! -z "$FILES" ]; then
    # Prettify all selected files
    echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

    # Add back the modified/prettified files to staging
    echo "$FILES" | xargs git add
fi