name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21.0"

      - name: Install client dependencies
        run: npm --prefix ./client install
      - name: Install server dependencies
        run: npm --prefix ./server install

      - name: Run client unit tests
        run: npm --prefix ./client run testOnce
      - name: Run server unit tests
        run: npm --prefix ./server run testOnce

      - name: Run client formatting checks
        run: npm --prefix ./client run formatCheck
      - name: Run server formatting checks
        run: npm --prefix ./server run formatCheck
